### ISSUE TITLE
Build fails when 'queryBeans = true'

### ISSUE THREAD

**Issue by cheese-stands-alone** [ebean-orm-tools/ebean-gradle-plugin#4]
Build normally works but when I try to generate query beans it fails with

`...
Caused by: java.lang.NullPointerException
	at org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.doAdd(DefaultDependencyHandler.java:119)
	at org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.add(DefaultDependencyHandler.java:94)
	at org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.add(DefaultDependencyHandler.java:89)
	at org.gradle.api.artifacts.dsl.DependencyHandler$add.call(Unknown Source)
	at org.avaje.ebean.gradle.EnhancePlugin.hookQueryBeans(EnhancePlugin.groovy:54)
	at org.avaje.ebean.gradle.EnhancePlugin$_apply_closure1.doCall(EnhancePlugin.groovy:35)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:221)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:145)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:315)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:225)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:138)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:35)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy23.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:82)
	... 64 more`

**Comment by rbygrave** [comment]
Is this a reproducable issue?

**Comment by rbygrave** [comment]
I'll close this for now.
